# **Sesi 2: Pengenalan dengan NumPy dan Arrays**

## **Praktek: Memasukkan dan mengakses data pada array​**

In [1]:
#import library numpy
#pip install numpy - pip3 install numpy
import numpy as np

In [2]:
#inisiasi array A
#np.array()
A = np.array([1, 3, 6, 3])
A

array([1, 3, 6, 3])

In [3]:
A.dtype

dtype('int64')

In [4]:
#inisiasi array A0 dengan int32
A0 = np.array([1, 3, 6, 3], dtype='int32')
A0.dtype

dtype('int32')

Array a memiliki tipe data int32 dan int64 yang keduanya sama-sama bertipekan integer. Perbedaan keduanya pada kapasitas penyimpanan data. 
*   Pada int32 mampu menampung hingga (-2,147,483,648 to +2,147,483,647)
*   Pada int64 mampu menampung hingga (-9,223,372,036,854,775,808 to +9,223,372,036,854,775,807)

In [5]:
#upcasting array B
B = np.array([1, 3, 6, 3.0])
B.dtype

dtype('float64')

In [6]:
#akses elemen array pertama (indeks=0)
print(A)
print(A[0])

[1 3 6 3]
1


In [7]:
#inisiasi array A1
A1 = np.array(["i"])
print(A1)
print(A1.dtype)

#inisiasi array A2
A2 = np.array(['i', 2, 4])
type(A2)
print(A2.dtype)

#<U1 = big-endian byte ordering unsigned ints size 1 byte, order in 1
#<U2 = big-endian byte ordering unsigned ints size 2 byte, order in 1

['i']
<U1
<U21


In [8]:
#print(A2)
#A2.mean()
#array berisikan string tidak bisa di looping untuk assign fungsi agregasi

['i' '2' '4']


TypeError: ignored




*   b1, i1, i2, i4, i8, u1, u2, u4, u8, f2, f4, f8, c8, c16, a 
   (representing bytes, ints, unsigned ints, floats, complex and 
    fixed-length strings of specified byte lengths)
*   int8,…,uint8,…,float16, float32, float64, complex64, complex128 
   (this time with bit sizes)
*  '>' represents big-endian byte ordering and < represents little-endian encoding.


In [ ]:
#akses elemen array ke-2 hingga ke-3
print(A[1:3])

## **Praktek: Membuat array otomatis dengan metode numpy​**

In [ ]:
a = np.empty([3,2], dtype = int)
print(a)

In [ ]:
#satu dimensi
b = np.zeros(5) 
print (b)

In [ ]:
#multidimensi
c = np.zeros((5,5)) 
print (c)

In [ ]:
#satu dimensi
d = np.ones(5) 
print (d)

In [ ]:
#satu dimensi
e = np.arange(5,10) 
print(e)

In [ ]:
#satu dimensi
f = np.linspace(5,10) 
print(f)
f.ndim

## **Praktek: Merubah dan menghapus elemen data pada array​**

In [ ]:
#import library numpy
import numpy as np

In [ ]:
#inisiasi array A
A = np.array([1, 3, 6, 3])

In [ ]:
#merubah elemen array A yang >5 menjadi 0
A[A > 5] = 0

In [ ]:
np.sqrt(A)

In [ ]:
#print hasil array yang telah dirubah
print(A)
import math
np.emath.sqrt(A)

In [ ]:
A

In [9]:
#menghapus elemen A pada indeks ke-0 sampai batas indeks 3 dengan np.delete(nama_array, indeks)
print(A)
A1 = np.delete(A, np.where(A[0:3]))
print(A1)

[1 3 6 3]
[3]


In [ ]:
#print hasil array yang telah dihapus elemen pertamanya (elemen dengan indeks = 0)
print(A1)

## **Praktek: Melakukan pengurutan dan penyaringan data pada array​**

In [10]:
#import library numpy
import numpy as np

In [11]:
#inisiasi array A
A = np.array([1, 3, 6, 3])

In [12]:
#urutkan array A
A2 = np.sort(A)

In [13]:
#print hasil array yang telah diurutkan
print(A2)

[1 3 3 6]


In [37]:
#filter elemen array berdasarkan indeks
print(A2)
x = [True, False, True, False]
A3 = A2[x]

[1 3 3 6]


In [38]:
#print hasil array yang telah difilter
print(A3)

[1 3]


In [16]:
#Filtering Array based on conditions
#buat filter yang hanya angka>3 yang disertakan
filter_arr = A > 3
A4 = A[filter_arr]

In [18]:
#print hasil array yang telah difilter
print(A4)
A4.dtype

[6]


dtype('int64')

## **Praktek: Membuat array 2 dimensi secara manual​**

In [ ]:
#import library numpy
import numpy as np

In [23]:
#buat array 2D dengan nama A5
A = np.array([1, 3, 6, 3])
A5 = np.array([[1, 3, 6, 3], [3, 6, 1, 3]])
print(A5.shape) #(baris, kolom)
print(A5.size) #total element 

(2, 4)
8


In [24]:
#print A5 dan cek dimensi array
print(A5)
print('dimensi array: ', A5.ndim)

[[1 3 6 3]
 [3 6 1 3]]
dimensi array:  2


## **Praktek: Konversi array 1 dimensi menjadi 2 dimensi​**

In [ ]:
#import library numpy 
import numpy as np

In [40]:
#inisiasi array A dan cek dimensinya
A = np.array([1, 3, 6, 3])
A7 = np.array([1, 3, 6, 3, 5])
print(A)
print('dimensi array: ', A.ndim)
print(A7.size)

[1 3 6 3]
dimensi array:  1
5


In [41]:
#ubah menjadi array 2x2 dan cek dimensinya
#shape array = *power* total element array (n,m)
#n = rows, m= columns
A8 = A7.reshape(2, 3)
print(A6)
print('dimensi array: ', A6.ndim)
print(A6.size)

ValueError: ignored

In [29]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [30]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
print(array1 + array2)

[ 6  8 10 12]
